### PR TITLE
Update Plextras.user.js

### PR DESCRIPTION
**Pull request by GertJanFrl**
Change URL! With the new URL you are not restricted to a specific commit, and it will always load the master file. No change needed from the user to update to a newer version of the file!

### CODE REVIEW

**Comment by GertJanFrl** [comment]
Found an error with the MIME type, undoing the change...

**Comment by andrewiankidd** [comment]
Github doesn't serve the right mimetype and rawgit cache never updates

Something that might work is calling $.get and appending the script to the head element, but could cause more issues

**Comment by GertJanFrl** [comment]
I see the issue with rawgit now yes.. And when I posted this comment I saw the issue with Github raw (mimetype).. There must be another way to make sure users won't fall to far behind with the updates and still don't have to do a thing themselves..

**Comment by GertJanFrl** [comment]
Plex loads jQuery from their "vendors.js" file. So maybe loading the custom Plextras.js last when jQuery has been loaded could be an option by using 
```
$.getScript('https://raw.githubusercontent.com/andrewiankidd/Plextras.js/master/Plextras.js', function() {
// Placing the init here
})
```

**Pull request closed without merging**
